[2025-03-27T01:28:05.064+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_geolocation_postgres_to_bq.postgres_to_gcs_batch_1 manual__2025-03-27T01:27:33.435534+00:00 [queued]>
[2025-03-27T01:28:05.093+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_geolocation_postgres_to_bq.postgres_to_gcs_batch_1 manual__2025-03-27T01:27:33.435534+00:00 [queued]>
[2025-03-27T01:28:05.097+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-03-27T01:28:05.523+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresToGCSOperator): postgres_to_gcs_batch_1> on 2025-03-27 01:27:33.435534+00:00
[2025-03-27T01:28:05.613+0000] {standard_task_runner.py:57} INFO - Started process 5618 to run task
[2025-03-27T01:28:05.754+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_geolocation_postgres_to_bq', 'postgres_to_gcs_batch_1', 'manual__2025-03-27T01:27:33.435534+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/geolocation_postgres_to_bq.py', '--cfg-path', '/tmp/tmppt5jj8tq']
[2025-03-27T01:28:05.871+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask postgres_to_gcs_batch_1
[2025-03-27T01:28:07.667+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-27T01:28:20.994+0000] {task_command.py:410} INFO - Running <TaskInstance: load_geolocation_postgres_to_bq.postgres_to_gcs_batch_1 manual__2025-03-27T01:27:33.435534+00:00 [running]> on host d0664e8a7014
[2025-03-27T01:29:38.006+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Blessing Angus' AIRFLOW_CTX_DAG_ID='load_geolocation_postgres_to_bq' AIRFLOW_CTX_TASK_ID='postgres_to_gcs_batch_1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T01:27:33.435534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T01:27:33.435534+00:00'
[2025-03-27T01:29:38.560+0000] {sql_to_gcs.py:155} INFO - Executing query
[2025-03-27T01:29:39.819+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-03-27T01:29:40.146+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 156, in execute
    cursor = self.query()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/postgres_to_gcs.py", line 118, in query
    cursor.execute(self.sql, self.parameters)
psycopg2.errors.UndefinedColumn: column "id" does not exist
LINE 1: SELECT * FROM public.geolocation ORDER BY id LIMIT 500000 OF...
                                                  ^

[2025-03-27T01:29:40.418+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=load_geolocation_postgres_to_bq, task_id=postgres_to_gcs_batch_1, execution_date=20250327T012733, start_date=20250327T012805, end_date=20250327T012940
[2025-03-27T01:29:40.606+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task postgres_to_gcs_batch_1 (column "id" does not exist
LINE 1: SELECT * FROM public.geolocation ORDER BY id LIMIT 500000 OF...
                                                  ^
; 5618)
[2025-03-27T01:29:40.654+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-27T01:29:41.107+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
