[2025-03-15T21:15:37.054+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_data_ingestion.ingest_sellers_data manual__2025-03-15T21:09:19.199161+00:00 [queued]>
[2025-03-15T21:15:37.334+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_data_ingestion.ingest_sellers_data manual__2025-03-15T21:09:19.199161+00:00 [queued]>
[2025-03-15T21:15:37.344+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-03-15T21:15:37.664+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_sellers_data> on 2025-03-15 21:09:19.199161+00:00
[2025-03-15T21:15:38.004+0000] {standard_task_runner.py:57} INFO - Started process 505 to run task
[2025-03-15T21:15:38.346+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_data_ingestion', 'ingest_sellers_data', 'manual__2025-03-15T21:09:19.199161+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp_jskponm']
[2025-03-15T21:15:38.679+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask ingest_sellers_data
[2025-03-15T21:15:39.890+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-15T21:15:55.076+0000] {task_command.py:410} INFO - Running <TaskInstance: postgres_data_ingestion.ingest_sellers_data manual__2025-03-15T21:09:19.199161+00:00 [running]> on host 8224d49c25d3
[2025-03-15T21:16:40.161+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Blessing' AIRFLOW_CTX_DAG_ID='postgres_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_sellers_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T21:09:19.199161+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T21:09:19.199161+00:00'
[2025-03-15T21:16:44.572+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
